/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddContactDialog: typeof import('./src/components/Contact/components/AddContactDialog.vue')['default']
    Avatar: typeof import('./src/components/Avatar/index.vue')['default']
    ChatMain: typeof import('./src/components/Chat/ChatMain.vue')['default']
    ChatMessage: typeof import('./src/components/Chat/ChatMessage.vue')['default']
    ChatSetting: typeof import('./src/components/Chat/ChatSetting.vue')['default']
    ContactList: typeof import('./src/components/Contact/ContactList.vue')['default']
    ContactSetting: typeof import('./src/components/Contact/ContactSetting.vue')['default']
    CropperDialog: typeof import('./src/components/NewUpload/components/CropperDialog.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    GroupChat: typeof import('./src/components/Chat/GroupChat.vue')['default']
    Header: typeof import('./src/components/Chat/Header.vue')['default']
    Menu: typeof import('./src/components/Menu/index.vue')['default']
    NewUpload: typeof import('./src/components/NewUpload/index.vue')['default']
    Notification: typeof import('./src/components/Media/Notification.vue')['default']
    Page: typeof import('./src/components/Page/Page.vue')['default']
    PictureCropper: typeof import('./src/components/Upload/PictureCropper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/Test.vue')['default']
    Upload: typeof import('./src/components/Upload/Upload.vue')['default']
    UploadImg: typeof import('./src/components/Upload/UploadImg.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
